CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    status VARCHAR(20) NOT NULL,
    assigned_user_id BIGINT NOT NULL REFERENCES app_users (id),
    CONSTRAINT cases_status_check
        CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'))
);

INSERT INTO app_users (name, email)
VALUES
    ('Maya Chen', 'maya.chen@example.com'),
    ('Noah Williams', 'noah.williams@example.com');

INSERT INTO cases (title, status, assigned_user_id)
VALUES
    (
        'Review supplier contract renewal',
        'OPEN',
        (SELECT id FROM app_users WHERE email = 'maya.chen@example.com')
    ),
    (
        'Resolve duplicate customer billing',
        'IN_PROGRESS',
        (SELECT id FROM app_users WHERE email = 'noah.williams@example.com')
    ),
    (
        'Confirm policy exception approval',
        'RESOLVED',
        (SELECT id FROM app_users WHERE email = 'maya.chen@example.com')
    );
