CREATE TABLE case_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL REFERENCES cases (id),
    note VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT case_activities_note_not_blank CHECK (BTRIM(note) <> '')
);

CREATE INDEX case_activities_case_created_at_idx
    ON case_activities (case_id, created_at DESC, id DESC);

INSERT INTO case_activities (case_id, note, created_at)
VALUES
    (
        (SELECT id FROM cases WHERE title = 'Review supplier contract renewal'),
        'Requested updated renewal terms from the supplier.',
        '2026-08-25T01:30:00Z'
    ),
    (
        (SELECT id FROM cases WHERE title = 'Review supplier contract renewal'),
        'Legal review is scheduled for Thursday.',
        '2026-08-26T04:15:00Z'
    ),
    (
        (SELECT id FROM cases WHERE title = 'Resolve duplicate customer billing'),
        'Confirmed both charges originated from the same invoice.',
        '2026-08-26T06:45:00Z'
    );
